### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by rozari0**

### CODE REVIEW

**Comment by Bnyro** [comment]
Thanks!
Are you still working on it or is it ready to become merged?

**Comment by rozari0** [comment]
> Thanks! Are you still working on it or is it ready to become merged?

I'm working on it. :)

**Comment by rozari0** [comment]
@Bnyro Fully ready to merge. ✌️

**Comment by Bnyro** [comment]
Thanks! I probably also need to set up all the secrets as I already did at the LibreTube repo?

**Comment by rozari0** [comment]
> Thanks! I probably also need to set up all the secrets as I already did at the LibreTube repo?

Yes, but it can run without them too.

**Pull request merged**
